name: SOOS DAST GitHub Actions

# Controls when the workflow will run
on: [push]

jobs:
  soos:
    permissions:
      security-events: write # for uploading code scanning alert info
    name: SOOS DAST Scan
    runs-on: ubuntu-latest
    steps:
      - name: Run SOOS DAST Scan
        uses: soos-io/soos-dast-github-action@5f8c23ccf8366ea0a58deeb5c804e0524267df43
        with:
          client_id: ${{ secrets.SOOS_CLIENT_ID }}
          api_key: ${{ secrets.SOOS_API_KEY }}
          project_name: ${{ github.repository }}
          scan_mode: 'baseline'
          api_url: "https://dev-api.soos.io/api/"
          target_url: "https://brokencrystals.com/"
          output_format: "sarif"
      - name: Upload SOOS DAST Report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
